/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Accounts__factory } from "./Accounts__factory";
export { Election__factory } from "./Election__factory";
