export const registryABI = [
  {
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [{ name: "test", internalType: "bool", type: "bool" }],
  },
  {
    constant: true,
    payable: false,
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "identifierHash", internalType: "bytes32", type: "bytes32" }],
    name: "getAddressForOrDie",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    constant: true,
    payable: false,
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "identifierHash", internalType: "bytes32", type: "bytes32" }],
    name: "getAddressFor",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    constant: true,
    payable: false,
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "identifier", internalType: "string", type: "string" }],
    name: "getAddressForStringOrDie",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    constant: true,
    payable: false,
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "identifier", internalType: "string", type: "string" }],
    name: "getAddressForString",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
];
